using = ["all"]

[machine]
name = "turtle"
cpu_count = 2
disk_size = 16384
memory = 4096
volumes = ["postgres_data"]

[[dependencies]]
name = "postgres"

    [dependencies.docker]
    image = "postgres:latest"
    ports = ["5432:5432"]
    environment = ["POSTGRES_PASSWORD=secret"]
    volumes = ["postgres_data:/var/lib/postgresql/data"]

[[repositories]]
name = "flowers"
remote = "git@gitlab.com:phamlequang/flowers.git"
local = "/Users/phamlequang/projects/flowers"
branch = "master"

    [[repositories.services]]
    name = "camellia"
    folder = "camellia"
    build = "cargo build"
    test = "cargo test"

        [repositories.services.docker]
        image = "rust:latest"
        ports = ["8000:8000"]
        working_dir = "/app"
        volumes = ["/Users/phamlequang/projects/flowers/camellia:/app"]
        env_file = ["/Users/phamlequang/projects/flowers/camellia/.env"]
        depends_on = ["postgres"]
        command = "cargo run"

    [[repositories.services]]
    name = "lotus"
    folder = "lotus"
    build = "cargo build"
    test = "cargo test"

        [repositories.services.docker]
        image = "rust:latest"
        ports = ["8001:8001"]
        working_dir = "/app"
        volumes = ["/Users/phamlequang/projects/flowers/lotus:/app"]
        env_file = ["/Users/phamlequang/projects/flowers/lotus/.env"]
        depends_on = ["postgres"]
        command = "cargo run"

[[groups]]
name = "all"
dependencies = ["postgres"]
repositories = ["flowers"]

[[groups]]
name = "rep"
repositories = ["flowers"]

[[groups]]
name = "dep"
dependencies = ["postgres"]
