[docker_machine]
name = "turtle"

[[dependencies]]
name = "postgres"
version = "11.1-alpine"

[[dependencies]]
name = "redis"
version = "5.0.3-alpine"

[[repositories]]
name = "flowers"
remote = "git@github.com:phamlequang/flowers.git"
local = "/Users/phamlequang/projects/flowers"
branch = "master"

    [[repositories.services]]
    name = "camellia"
    folder = "camellia"

    [[repositories.services]]
    name = "lotus"
    folder = "lotus"
