[docker_machine]
name = "turtle"
cpu_count = 2
disk_size = 10240
memory = 4096

[[dependencies]]
name = "postgres"
version = "11.1-alpine"

[[dependencies]]
name = "redis"
version = "5.0.3-alpine"

[[repositories]]
name = "flowers"
remote = "git@gitlab.com:phamlequang/flowers.git"
local = "/Users/phamlequang/projects/flowers"
branch = "master"

    [[repositories.services]]
    name = "camellia"
    folder = "camellia"
    build = "cargo build"
    test = "cargo test"
    run = "cargo run"

    [[repositories.services]]
    name = "lotus"
    folder = "lotus"
    build = "cargo build"
    test = "cargo test"
    run = "cargo run"

[[groups]]
name = "forest"
dependencies = ["postgres", "redis"]
repositories = ["flowers"]

[[groups]]
name = "dep"
dependencies = ["postgres", "redis"]

[[groups]]
name = "rep"
repositories = ["flowers"]
