[docker_machine]
name = "turtle"
cpu_count = 2
disk_size = 16384
memory = 4096

[[dependencies]]
name = "postgres"

    [dependencies.docker]
        image = "postgres:11.1-alpine"
        ports = ["5432:5432"]
        volumes = ["postgres_data:/var/lib/postgresql/data"]

[[repositories]]
name = "flowers"
remote = "git@gitlab.com:phamlequang/flowers.git"
local = "/Users/phamlequang/projects/flowers"
branch = "master"

    [[repositories.services]]
    name = "camellia"
    folder = "camellia"
    build = "cargo build"
    test = "cargo test"

        [repositories.services.docker]
        image = "camellia"
        ports = ["8000:8000"]
        command = "cargo run"

    [[repositories.services]]
    name = "lotus"
    folder = "lotus"
    build = "cargo build"
    test = "cargo test"

        [repositories.services.docker]
        image = "lotus"
        ports = ["8001:8001"]
        command = "cargo run"

[[groups]]
name = "forest"
dependencies = ["postgres"]
repositories = ["flowers"]
