version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
  camellia:
    image: rust:latest
    ports:
      - 8000:8000
    working_dir: /app
    volumes:
      - /Users/phamlequang/projects/flowers/camellia:/app
    env_file:
      - /Users/phamlequang/projects/flowers/camellia/.env
    depends_on:
      - postgres
      - redis
    command: cargo run
    labels:
      - author=phamlequang
  lotus:
    image: rust:latest
    ports:
      - 8001:8001
    working_dir: /app
    volumes:
      - /Users/phamlequang/projects/flowers/lotus:/app
    env_file:
      - /Users/phamlequang/projects/flowers/lotus/.env
    depends_on:
      - postgres
    command: cargo run
volumes:
  postgres_data:
    external: false
  redis_data:
    external: false
