project = "forest"
using = ["all"]

[machine]
name = "turtle"
cpu_count = 2
disk_size = 16384
memory = 4096
volumes = ["postgres_data", "redis_data"]

[[dependencies]]
name = "postgres"

[dependencies.docker]
image = "postgres:latest"
ports = ["5432:5432"]
volumes = ["postgres_data:/var/lib/postgresql/data"]
environment = ["POSTGRES_PASSWORD=secret"]

[[dependencies]]
name = "redis"

[dependencies.docker]
image = "redis:latest"
ports = ["6379:6379"]
volumes = ["redis_data:/data"]

[[repositories]]
name = "flowers"
remote = "git@gitlab.com:phamlequang/flowers.git"
local = "/Users/phamlequang/projects/flowers"
branch = "master"

[[services]]
name = "camellia"
repo = "flowers"
folder = "camellia"
build = "cargo build"
test = "cargo test"

[services.docker]
image = "rust:latest"
ports = ["8000:8000"]
working_dir = "/app"
volumes = ["{SERVICE_DIR}:/app"]
env_file = ["{SERVICE_DIR}/.env"]
depends_on = ["postgres", "redis"]
command = "cargo run"

[[services]]
name = "lotus"
repo = "flowers"
folder = "lotus"
build = "cargo build"
test = "cargo test"

[services.docker]
image = "rust:latest"
ports = ["8001:8001"]
working_dir = "/app"
volumes = ["{SERVICE_DIR}:/app"]
env_file = ["{SERVICE_DIR}/.env"]
depends_on = ["postgres"]
command = "cargo run"

[[groups]]
name = "all"
dependencies = ["postgres", "redis"]
services = ["camellia", "lotus"]

[[groups]]
name = "svc"
services = ["camellia", "lotus"]

[[groups]]
name = "dep"
dependencies = ["postgres", "redis"]
