project = "forest"
using = ["all"]

[machine]
name = "turtle"
cpu_count = 2
disk_size = 16384
memory = 4096

[[dependencies]]
name = "postgres"

[dependencies.docker]
image = "postgres:latest"
ports = ["5432:5432"]
volumes = ["postgres_data:/var/lib/postgresql/data"]
environment = ["POSTGRES_PASSWORD=secret"]

[[dependencies]]
name = "redis"

[dependencies.docker]
image = "redis:latest"
ports = ["6379:6379"]
volumes = ["redis_data:/data"]

[[repositories]]
name = "flowers"
remote = "git@gitlab.com:phamlequang/flowers.git"
local = "~/projects/flowers"

[[actions]]
name = "cargo"
build = "cargo build"
test = "cargo test"

[[services]]
name = "camellia"
repo = "flowers"
folder = "camellia"
action = "cargo"

[services.docker]
image = "camellia"
ports = ["8000:8000"]
working_dir = "/app/camellia"
volumes = ["{REPO_DIR}:/app"]
env_file = ["{SERVICE_DIR}/.env"]
depends_on = ["postgres", "redis"]
command = "../wait-for-it.sh postgres:5432 -- cargo run"
labels = ["author=phamlequang"]

[services.docker.build]
context = "{REPO_DIR}"
docker_file = "camellia/Dockerfile"

[[services]]
name = "lotus"
repo = "flowers"
folder = "lotus"
action = "cargo"

[services.docker]
image = "rust:latest"
ports = ["8001:8001"]
working_dir = "/app"
volumes = ["{SERVICE_DIR}:/app"]
env_file = ["{SERVICE_DIR}/.env"]
depends_on = ["postgres"]
command = "cargo run"

[[groups]]
name = "all"
dependencies = ["postgres", "redis"]
services = ["camellia", "lotus"]

[[groups]]
name = "svc"
services = ["camellia", "lotus"]

[[groups]]
name = "dep"
dependencies = ["postgres", "redis"]
