version: '3'
volumes:
  postgres_data:
    external: false
  redis_data:
    external: false
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
