project = "sample"
using = ["all"]

[machine]
name = "turtle"
cpu_count = 2
disk_size = 16384
memory = 4096
dns = "dev.turtle.com"

[[dependencies]]
name = "postgres"

[dependencies.docker]
image = "postgres:latest"
container_name = "postgres"
ports = ["5432:5432"]
volumes = ["postgres_data:/var/lib/postgresql/data"]
environment = ["POSTGRES_PASSWORD=secret"]

[[dependencies]]
name = "redis"

[dependencies.docker]
image = "redis:latest"
container_name = "redis"
ports = ["6379:6379"]
volumes = ["redis_data:/data"]

[[repositories]]
name = "flowers"
remote = "git@gitlab.com:phamlequang/flowers.git"
local = "~/projects/flowers"

[[actions]]
name = "cargo"
build = "cargo build"
test = "cargo test"

[[patterns]]
format = "{APP_DIR}"
expand = "/rust/app/flowers"

[[patterns]]
format = "{RUN_CMD}"
expand = "../wait-for-it.sh postgres:5432 -- cargo run"

[[services]]
name = "camellia"
repo = "flowers"
folder = "camellia"
action = "cargo"

[services.docker]
image = "camellia"
container_name = "camellia"
ports = ["8000:8000"]
working_dir = "{APP_DIR}/camellia"
volumes = ["{REPO_DIR}:{APP_DIR}"]
env_file = ["{SERVICE_DIR}/.env"]
depends_on = ["postgres", "redis"]
command = "{RUN_CMD}"
labels = ["author=phamlequang"]

[services.docker.build]
context = "{REPO_DIR}"
docker_file = "camellia/Dockerfile"

[[services]]
name = "lotus"
repo = "flowers"
folder = "lotus"
action = "cargo"

[services.docker]
image = "lotus"
container_name = "lotus"
ports = ["8001:8001"]
working_dir = "{APP_DIR}/lotus"
volumes = ["{REPO_DIR}:{APP_DIR}"]
env_file = ["{SERVICE_DIR}/.env"]
depends_on = ["postgres", "redis"]
command = "{RUN_CMD}"
labels = ["author=phamlequang"]

[services.docker.build]
context = "{REPO_DIR}"
docker_file = "lotus/Dockerfile"

[[groups]]
name = "all"
dependencies = ["postgres", "redis"]
services = ["camellia", "lotus"]

[[groups]]
name = "svc"
services = ["camellia", "lotus"]

[[groups]]
name = "dep"
dependencies = ["postgres", "redis"]
